/**
 * "Remove natural features" filter for the Difference view.
 *
 * Two classes of NATURAL height differences can't be simulated from the seed
 * and would otherwise litter the map as false terraforming:
 *
 *  - Tree canopy (feature decoration is never generated by the noise
 *    pipeline): reads as a small positive bump — the current surface sits a
 *    tree-height above the simulated bare ground, on top of ground that
 *    matches the simulation right next to it.
 *  - Carver ravines / cave mouths (vanilla "carvers" run as a separate
 *    generation stage that deepslate doesn't implement): read as a narrow
 *    negative slot cut into ground whose rim matches the simulation.
 *
 * Both have a morphological signature — a feature NARROWER than some window
 * sitting in otherwise-matching terrain — which is what this filter keys on,
 * deliberately ignoring surface color (over 40% of real canopy pixels aren't
 * even green-dominant in BlueMap's shaded output).
 *
 * Known mis-reads, and why the map exposes this as a toggle rather than
 * always-on: player structures smaller than the windows are suppressed too —
 * a lone pillar or hut under ~13 blocks wide, or a trench under ~25 wide, on
 * natural ground. Large builds, platforms, quarries and terraforming keep a
 * local min/max far from the simulated ground and always survive.
 */

/** Positive diffs up to this magnitude can be canopy (user-tuned: 16). */
const CANOPY_MAX_DIFF = 16;
/** Half-width of the canopy window — 5x5 (user-tuned): only bumps narrower
 *  than ~5 blocks count as canopy, so any build wider than a sapling keeps
 *  an elevated local minimum and stays visible. */
const CANOPY_RADIUS = 2;
/** Negative diffs up to this magnitude can be carver ravines. Kept moderate
 *  (user-tuned down from 64) so deep cuts always show even in narrow slots. */
const CARVE_MAX_DIFF = 32;
/** Half-width of the carve window (17x17, user-tuned down from 25x25) so
 *  long-but-moderate artificial cuts (canals, sunken roads) survive. */
const CARVE_RADIUS = 8;
/** How close the window's extreme must come to the simulated ground to count
 *  as "matching". Deliberately tight (user-tuned down from 5): with a loose
 *  tolerance, WIDE terraforms with minor grade changes (a plaza levelled +4,
 *  a road graded -3) read as "matching ground" across their whole area and
 *  vanish. At 1, only terrain that truly matches the fresh-world simulation
 *  counts as natural, so even minor-grade terraforming stays visible. */
const GROUND_MATCH_TOL = 1;

/** Sentinel for columns with no BlueMap data. */
export const NO_DATA = -4096;

/**
 * Absolute |current − simulated| per column, with natural canopy/carve
 * artifacts suppressed to 0. `cur` and `sim` are row-major size×size grids.
 * Windows clamp at the grid border (the outermost ~CARVE_RADIUS blocks of a
 * tile may classify slightly differently than they would with neighbors).
 */
export function filterNaturalArtifacts(
  cur: Int16Array,
  sim: Int16Array,
  size: number,
): Int16Array {
  const locMin = slidingExtreme(cur, size, CANOPY_RADIUS, false);
  const locMax = slidingExtreme(cur, size, CARVE_RADIUS, true);
  const out = new Int16Array(size * size);
  for (let i = 0; i < out.length; i++) {
    if (cur[i] === NO_DATA) continue;
    const d = cur[i] - sim[i];
    // Ground-match tests are ONE-SIDED so mixed natural terrain still passes:
    // a ravine rim under tree canopy pushes the window max ABOVE the simulated
    // ground (still natural), and trees beside a carved slot pull the window
    // min BELOW it. The preserved cases are unaffected — a player platform
    // keeps its local min above sim, a player pit keeps its local max below.
    if (d > 0 && d <= CANOPY_MAX_DIFF && locMin[i] <= sim[i] + GROUND_MATCH_TOL) {
      continue; // bump on (or above) matching ground -> tree / boulder
    }
    if (d < 0 && -d <= CARVE_MAX_DIFF && locMax[i] >= sim[i] - GROUND_MATCH_TOL) {
      continue; // narrow slot in (or under) matching ground -> ravine / cave mouth
    }
    out[i] = Math.abs(d);
  }
  return out;
}

/** Raw |current − simulated| per column (the unfiltered variant). */
export function absoluteDiff(cur: Int16Array, sim: Int16Array, size: number): Int16Array {
  const out = new Int16Array(size * size);
  for (let i = 0; i < out.length; i++) {
    if (cur[i] !== NO_DATA) out[i] = Math.abs(cur[i] - sim[i]);
  }
  return out;
}

/**
 * Separable sliding-window min or max (row pass then column pass), ignoring
 * NO_DATA cells; O(n·r) which is trivial at tile size.
 */
function slidingExtreme(
  grid: Int16Array,
  size: number,
  radius: number,
  isMax: boolean,
): Int16Array {
  const pass1 = new Int16Array(size * size);
  const pass2 = new Int16Array(size * size);
  const worst = isMax ? -32768 : 32767;
  for (let z = 0; z < size; z++) {
    for (let x = 0; x < size; x++) {
      let best = worst;
      const lo = Math.max(0, x - radius);
      const hi = Math.min(size - 1, x + radius);
      for (let k = lo; k <= hi; k++) {
        const v = grid[z * size + k];
        if (v === NO_DATA) continue;
        if (isMax ? v > best : v < best) best = v;
      }
      pass1[z * size + x] = best;
    }
  }
  for (let x = 0; x < size; x++) {
    for (let z = 0; z < size; z++) {
      let best = worst;
      const lo = Math.max(0, z - radius);
      const hi = Math.min(size - 1, z + radius);
      for (let k = lo; k <= hi; k++) {
        const v = pass1[k * size + x];
        if (v === -32768 || v === 32767) continue;
        if (isMax ? v > best : v < best) best = v;
      }
      pass2[x + z * size] = best;
    }
  }
  return pass2;
}
